version: '3.1'
services:
  keycloak:
    image: jboss/keycloak:6.0.1
    container_name: keycloak-local
    user: ${CURRENT_UID}
    command: ["-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
    networks:
      - database
      - vcxauth
    ports:
      - "9443:8443"
      - "9990:9990"
      - "9993:9993"
#      - "9080:8080"
    env_file:
      - variables-local.env
    volumes:
      - ./keycloak/standalone/configuration:/opt/jboss/keycloak/standalone/configuration:Z
#      - ./keycloak/themes/vcx:/opt/jboss/keycloak/themes/vcx:Z
#      - ./keycloak/themes/housingdb:/opt/jboss/keycloak/themes/housingdb:Z
    depends_on:
      - postgres
  postgres:
    image: postgres:10
    container_name: postgres-local
    user: ${CURRENT_UID}
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data:Z
    env_file:
      - variables-local.env
    ports:
      - "5435:5432"
    networks:
      - database
networks:
  database:
    driver: bridge
  vcxauth:
    driver: bridge